# Site settings
title: Kai Herron
email: kaiherron28@gmail.com
description: This is Kai Herron's website. > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "kai-herron.github.io" # the base hostname & protocol for your site

twitter_username: @bigmamikai
github_username: kai-herron

# Build settings
markdown: kramdown
